language: ruby

rvm:
  - 2.3.3

install:
  - gem install rubocop
  - gem install fastimage
  - bundle install

script:
  - rubocop lib/img_checker.rb
  - gem build img_checker.gemspec
  - gem install *.gem
  - bundle exec rspec spec
