language: ruby

rvm:
  - 2.3.3

install:
  - gem install rubocop
  - gem install fastimage

script:
  - rubocop lib/img_checker.rb
  - gem build img_checker.gemspec
  - gem install *.gem
  - cd test
  - img_checker
